version: '3.7'
services:
  nethermind:
    init: true
    container_name: poa-validator
    image: nethermind/nethermind:latest
    environment:
      NETHERMIND_CONFIG: sokol
      NETHERMIND_AURACONFIG_FORCESEALING: "true"
      NETHERMIND_ETHSTATSCONFIG_ENABLED: "true"
      NETHERMIND_ETHSTATSCONFIG_SERVER: "wss://sokol-netstat.poa.network/api"
      NETHERMIND_ETHSTATSCONFIG_SECRET: "${ETHSTATS_SECRET}"
      NETHERMIND_ETHSTATSCONFIG_CONTACT: "${ETHSTATS_CONTACT}"
      NETHERMIND_ETHSTATSCONFIG_NAME: "${ETHSTATS_ID}"
      NETHERMIND_INITCONFIG_ISMINING: "true"
      NETHERMIND_INITCONFIG_STORERECEIPTS: "false"
      NETHERMIND_KEYSTORECONFIG_TESTNODEKEY: $KEY
      NETHERMIND_METRICSCONFIG_ENABLED: "true"
      NETHERMIND_METRICSCONFIG_NODENAME: $ETHSTATS_ID
      NETHERMIND_METRICSCONFIG_PUSHGATEWAYURL: https://metrics.nethermind.io/metrics/validators-Ifa0eigee0deigah8doo5aisaeNa8huichahk5baip2daitholaeh4xiey0iec1vai6Nahxae1aeregul5Diehae7aeThengei7X
      NETHERMIND_METRICSCONFIG_INTERVALSECONDS: 30
      NETHERMIND_MININGCONFIG_MINGASPRICE: "1000000000"
      NETHERMIND_MININGCONFIG_TARGETBLOCKGASLIMIT: "12500000"
      NETHERMIND_PRUNINGCONFIG_ENABLED: "false"
      NETHERMIND_SEQCONFIG_MINLEVEL: "Info"
      NETHERMIND_SEQCONFIG_SERVERURL: "https://seq.nethermind.io"
      NETHERMIND_SEQCONFIG_APIKEY: $SEQAPIKEY
      NETHERMIND_SYNCCONFIG_FASTSYNC: "true"
      NETHERMIND_SYNCCONFIG_FASTBLOCKS: "true"
      NETHERMIND_SYNCCONFIG_DOWNLOADBODIESINFASTSYNC: "false"
      NETHERMIND_SYNCCONFIG_DOWNLOADRECEIPTSINFASTSYNC: "false"
    volumes:
      - ./data/logs:/nethermind/logs
      - ./data/keystore:/nethermind/keystore
      - ./data/nethermind_db:/nethermind/nethermind_db
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
